language: node_js
node_js:
  - "0.11"
  - "0.10"

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run update-webdriver
  - node_modules/.bin/webdriver-manager start > /dev/null &
  - sleep 1 # give server time to start

script:
  - node_modules/.bin/cucumber.js --format pretty
